import MainLayout from "../components/main/MainLayout"
import Sidebar from "../components/sidebar/Sidebar"
import styles from '../../styles/styles.module.css';
import Header from "../components/header/Header";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
